#define IOCTL_MAXCMD_LED 3
#define IOCTL_LED_LKM_MAGIC 0xA8
#define IOCTL_POWER_ON _IO(IOCTL_LED_LKM_MAGIC, 0)
#define IOCTL_POWER_OFF _IO(IOCTL_LED_LKM_MAGIC, 1)
#define IOCTL_POWER_READ _IOR(IOCTL_LED_LKM_MAGIC, 2, int)
